# Generated by Django 5.2.17 on 2026-09-20 04:00

import common.forms
import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=80, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('current_quantity', models.PositiveIntegerField(default=0, editable=False)),
                ('minimum_stock_level', models.PositiveIntegerField(default=5)),
                ('unit', models.CharField(default='pcs', max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='products/', validators=[common.forms.validate_image])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.category')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['name'],
                'permissions': [('view_dashboard', 'Can view dashboard'), ('view_reports', 'Can view inventory reports'), ('stock_in', 'Can receive stock'), ('stock_out', 'Can issue stock')],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'Stock in'), ('OUT', 'Stock out')], max_length=3)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_before', models.PositiveIntegerField()),
                ('quantity_after', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('reference_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('transaction_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'current_quantity'], name='inventory_p_is_acti_04b6e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('cost_price__gte', 0), ('selling_price__gte', 0)), name='product_nonnegative_prices'),
        ),
        migrations.AddConstraint(
            model_name='stocktransaction',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='movement_positive_quantity'),
        ),
        migrations.AddConstraint(
            model_name='stocktransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('quantity_after', django.db.models.expressions.CombinedExpression(models.F('quantity_before'), '+', models.F('quantity'))), ('transaction_type', 'IN')), models.Q(('quantity_after', django.db.models.expressions.CombinedExpression(models.F('quantity_before'), '-', models.F('quantity'))), ('transaction_type', 'OUT')), _connector='OR'), name='movement_balanced'),
        ),
    ]
